### ISSUE TITLE
Backend error when updating question

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#122]
error when trying to update question:

```
questions_api       | INFO:     192.168.128.5:51128 - "PUT /questions HTTP/1.1" 500 Internal Server Error
api_gateway         | INFO:     192.168.128.1:35908 - "PUT /questions HTTP/1.1" 500 Internal Server Error
api_gateway         | ERROR:    Exception in ASGI application
api_gateway         | Traceback (most recent call last):
questions_api       | ERROR:    Exception in ASGI application
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
questions_api       | Traceback (most recent call last):
api_gateway         |     result = await app(  # type: ignore[func-returns-value]
questions_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
api_gateway         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
questions_api       |     result = await app(  # type: ignore[func-returns-value]
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
questions_api       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |     return await self.app(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
api_gateway         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
questions_api       |     return await self.app(scope, receive, send)
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
questions_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |     await super().__call__(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
questions_api       |     await super().__call__(scope, receive, send)
api_gateway         |     await self.middleware_stack(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
questions_api       |     await self.middleware_stack(scope, receive, send)
api_gateway         |     raise exc
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
questions_api       |     raise exc
api_gateway         |     await self.app(scope, receive, _send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
questions_api       |     await self.app(scope, receive, _send)
api_gateway         |     await self.simple_response(scope, receive, send, request_headers=headers)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response        
questions_api       |     await self.app(scope, receive, send)
api_gateway         |     await self.app(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
questions_api       |     raise exc
api_gateway         |     raise exc
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
questions_api       |     await self.app(scope, receive, sender)
api_gateway         |     await self.app(scope, receive, sender)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__        
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__        
questions_api       |     raise e
api_gateway         |     raise e
questions_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__        
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__        
questions_api       |     await self.app(scope, receive, send)
api_gateway         |     await self.app(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
questions_api       |     await route.handle(scope, receive, send)
api_gateway         |     await route.handle(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
questions_api       |     await self.app(scope, receive, send)
api_gateway         |     await self.app(scope, receive, send)
questions_api       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
questions_api       |     response = await func(request)
api_gateway         |     response = await func(request)
questions_api       |                ^^^^^^^^^^^^^^^^^^^
api_gateway         |                ^^^^^^^^^^^^^^^^^^^
questions_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
questions_api       |     raw_response = await run_endpoint_function(
api_gateway         |     raw_response = await run_endpoint_function(
questions_api       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
questions_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
questions_api       |     return await dependant.call(**values)
api_gateway         |     return await dependant.call(**values)
questions_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
questions_api       |   File "/app/main.py", line 36, in update_question_info
questions_api       |     return qc.update_question_info(r.question_id, r.title, r.description, r.category, r.complexity, r.session_id)  
questions_api       |                                                                                                     ^^^^^^^^^^^^   
api_gateway         |   File "/main.py", line 76, in handle_request
questions_api       |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 734, in __getattr__
api_gateway         |     response = response.json()
questions_api       |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
api_gateway         |                ^^^^^^^^^^^^^^^
questions_api       | AttributeError: 'UpdateQuestionInfo' object has no attribute 'session_id'
api_gateway         |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 756, in json
api_gateway         |     return jsonlib.loads(self.text, **kwargs)
api_gateway         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
api_gateway         |     return _default_decoder.decode(s)
api_gateway         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
api_gateway         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
api_gateway         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_gateway         |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
api_gateway         |     raise JSONDecodeError("Expecting value", s, err.value) from None
api_gateway         | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by EvitanRelta** [comment]
old bug.
seems to be fixed already
